✅ Step 5 — Create GitLab CI File
Create .gitlab-ci.yml
stages:
  - build
  - deploy
variables:
  PROJECT_ID: "project-5f31727c-d8b4-4d10-bc3"
  REGION: "asia-south1"
  SERVICE_NAME: "demoapp"
  REPOSITORY: "demo-repo"
before_script:
  - echo $GCLOUD_SERVICE_KEY | base64 -d > gcloud-key.json
  - gcloud auth activate-service-account --key-file gcloud-key.json
  - gcloud config set project $PROJECT_ID
  - gcloud auth configure-docker $REGION-docker.pkg.dev
build:
  stage: build
  image: google/cloud-sdk:latest
  script:
    - docker build -t asia-south1-docker.pkg.dev/project-5f31727c-d8b4-4d10-bc3/demo-repo
    - docker push asia-south1-docker.pkg.dev/project-5f31727c-d8b4-4d10-bc3/demo-repo
deploy:
  stage: deploy
  image: google/cloud-sdk:latest
  script:
    - gcloud run deploy $SERVICE_NAME \
        --image asia-south1-docker.pkg.dev/project-5f31727c-d8b4-4d10-bc3/demo-repo \
        --region $REGION \
        --platform managed \
        --allow-unauthenticated
 
